### ISSUE TITLE
Return the saved model

### ISSUE THREAD

**Issue by colembolos** [rootstrap/yaaf#41]
What about some function that saves the record and returns the model? Kinda the create method, I would like to prevent additional steps or functions inside of the ModelForm to return that model.

Something like this:

```
class MyController < ApplicationController
  def create
    model_form = ModelForm.new(params)
    @event = model_form.create!
  end
end
```

**Comment by santib** [comment]
The problem is that in a form object you could potentially have multiple models. To implement something like this, we'd need to introduce the concept of a "primary model".. thoughts? 

cc: @juanmanuelramallo

**Comment by juanmanuelramallo** [comment]
This is a good use case. 

What about doing something like (considering the model is called "Event")

in the form object
```ruby
class EventForm < ApplicationForm
  ...

  def event
    # return the event instance here 
  end
end
```

in the controller:
```ruby
class EventsController < ApplicationController
  ...

  def create
    event_form = EventForm.new(params)
    event_form.save!
    @event = event_form.event
  end
end
```

Would that work? 

Otherwise we should somehow provide the concept of a primary model no?

**Comment by colembolos** [comment]
@juanmanuelramallo It is a good idea, in such a case if we do not have the primary model concept that event should return an array, right?

**Comment by juanmanuelramallo** [comment]
No I don't think it should return an array, it should just return the model instance you need to use in your controller
