### ISSUE TITLE
Deprecation warning in Rails 6.1

### ISSUE THREAD

**Issue by Shaglock** [rootstrap/yaaf#47]
**Is your feature request related to a problem? Please describe.**
So I am using rails 6.1 and get this deprecation warning. 
```DEPRECATION WARNING: Enumerating ActiveModel::Errors as a hash has been deprecated.
In Rails 6.1, `errors` is an array of Error objects,
therefore it should be accessed by a block with a single block
parameter like this:

person.errors.each do |error|
  attribute = error.attribute
  message = error.message
end

You are passing a block expecting two parameters,
so the old hash behavior is simulated. As this is deprecated,
this will result in an ArgumentError in Rails 6.2.
```

**Describe the solution you'd like**
I guess we have to change [promote_errors](https://github.com/rootstrap/yaaf/blob/master/lib/yaaf/form.rb#L33
) a bit, but as I understand this new behavior will not work in rails < 6.1? I could make a PR, but I don't know how to make it compatible with  rails versions < 6.1.

**Additional context**
https://github.com/rails/rails/pull/32313

**Comment by santib** [comment]
Hey @Shaglock thanks for reporting the issue. You are right, we need to update the `promote_errors` method. I think we have two options:
1. Make a breaking change and a major version release
2. Add a conditional and use the correct code. Something like
```ruby
if Rails::VERSION::MAJOR < 6 ||  Rails::VERSION::MAJOR == 6 && Rails::VERSION::MINOR == 0
  # Do the old thing
else
  # Do it the new way
end
```

I think I'd go with the second option, thoughts? Feel free to open a PR and I'll help you get it merged 😄 

cc @juanmanuelramallo

**Comment by Shaglock** [comment]
Hello, @santib! 
Thank you for replying.
Completely forgot about this conditions. I think I'll try to add PR for 2nd option this week!
