### ISSUE TITLE
[Bug] Double Validation On Save (?)

### ISSUE THREAD

**Issue by thewatts** [rootstrap/yaaf#65]
This isn't quite a bug report - but wasn't sure if this is intended behavior.

We use form objects quite a bit - and have run into this same issue on our custom forms.

When calling `save`, validations are run - including model validations (which, is what we would expect). However, once those validations pass, the models are all saved via `save!` inside of a transaction.

That [`save!`](https://github.com/rootstrap/yaaf/blob/master/lib/yaaf/form.rb#L44), however, will end up calling model validations a _second_ time.

For basic validations, this doesn't matter that much as they are done in memory - but any type of validation (like a uniqueness validation) will hit the database a second time (the first being in the [`invalid?`](https://github.com/rootstrap/yaaf/blob/master/lib/yaaf/form.rb#L15) call, and the second in the `save!`).

Would it be better to call `save!(validate: false)` on each of the models, as they are already being validated just a few lines earlier?

**Comment by santib** [comment]
Hi @thewatts, you are completely right about it. I have thought about it before but never decided to make the change because I didn't find a case where running validations twice would be harmful. Now that you bring up a performance concern (hitting DB twice instead of once) I think we can revisit it.

I would be fine calling `save!(validate: false)` on each of the models, but I would like to double-check that we aren't breaking anything before doing that.

@juanmanuelramallo any thoughts on this?

**Comment by juanmanuelramallo** [comment]
Makes total sense to me. We should only run the validations once.

**Comment by santib** [comment]
@thewatts Would you like to open a PR?

**Comment by thewatts** [comment]
@santib sure! 

It'll take me a few days - but I'll take a swing at it :)

**Comment by thewatts** [comment]
Sorry - to clarify - it's not going to take me a few days to program it, I just don't have a lot of time margin right now - so it's going to be a little bit ;)

**Comment by thewatts** [comment]
In digging into the project, I noticed that there was a PR for this already (#28), but it was closed.

Just confirming that this is something that is now wanted for YAAF before I submit a PR 😄

**Comment by santib** [comment]
> In digging into the project, I noticed that there was a PR for this already (#28), but it was closed.
> 
> Just confirming that this is something that is now wanted for YAAF before I submit a PR 😄

Haha good catch! I completely forgot about that conversation. I guess @juanmanuelramallo changed his mind now, I'm good  with the change 😄
